version: '3.8'
services:
  cv_api_hawkeye:
    image: pollito500/hawkeye-app:1.4
    build: 
      context: .
      dockerfile: Dockerfile
    ports: 
      - '8080:8080'

#Docker compose para iniciar opencv api