import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";
import Button from "~/components/Button";
import { api } from "~/utils/api";
import Image from "next/image";

const Launch: NextPage = () => {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-[url('/img/bg-alt-1920x1080.png')] bg-top bg-no-repeat px-[32px]">
        <div className="mx-auto flex w-full max-w-fit flex-col items-center gap-[32px]">
          <Image
            src={"/img/imagotype.png"}
            alt="Hawkeye logo"
            width={256}
            height={256}
          />
          <div className="flex flex-col items-center justify-center gap-[16px]">
            <h1 className="text-center text-4xl font-bold text-foreground-important">
              Welcome to Hawkeye
            </h1>
            <p className="text-center text-base font-normal text-foreground">
              Elevate your game to the next level with{" "}
              <br className="hidden sm:block" /> the power of AI.
            </p>
          </div>
          <Link href={"/log-in"} className="flex w-full flex-col">
            <Button
              style="primary"
              label="Get started"
              iconPosition="right"
              type="button"
              icon={
                <svg
                  width="20"
                  height="20"
                  viewBox="0 0 20 20"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    d="M8 15L6.9375 13.9375L10.875 10L6.9375 6.0625L8 5L13 10L8 15Z"
                    className="fill-background"
                  />
                </svg>
              }
            />
          </Link>
        </div>
      </main>
    </>
  );
};

export default Launch;

/*

        <h1 className="text-center text-4xl font-bold text-foreground-important">
          Welcome to Hawkeye
        </h1>
        <p className="text-center text-base font-normal text-foreground">
          Elevate your game to the next level with the power of AI.
        </p>
        <Link href={"/log-in"} className="flex w-full">
          <Button
            style="primary"
            label="Get started"
            iconPosition="right"
            type="button"
            icon={
              <svg
                width="20"
                height="20"
                viewBox="0 0 20 20"
                fill="none"
                xmlns="http://www.w3.org/2000/svg"
              >
                <path
                  d="M8 15L6.9375 13.9375L10.875 10L6.9375 6.0625L8 5L13 10L8 15Z"
                  className="fill-background"
                />
              </svg>
            }
          />
        </Link>

*/
